### ISSUE TITLE
Experience so far

### ISSUE THREAD

**Issue by bflamig** [hselasky/hpsjam#6]
Just wanted to leave you a comment saying I tried out your latest version (1.06). I do like the crystal clear sound which makes my fiddle sound so much better than with the compressed audio of Jamulus. I did have to set the buffer size to 256 (instead of a preferred 64) , otherwise I get way too may xruns. With the higher buffer size, I don't get many (if any) xruns, but do get occasional glitches which I presume are from dropped/delayed packets, which do get annoying. Not sure why this is occurring since I'm running the client and server on the same machine. I tried this on a Raspberry Pi 400 (the brand new, just out,  combined keyboard/Pi unit -- nice!) which runs cool at 2.1 Ghz, unlike the earlier Pi 4 which tends to run quite hot when running audio software. I haven't tested any other configurations yet.

Here are the jack parameters I'm using: jackd -T -P95 -p16 -t2000 -d alsa -dhw:2 -p 128 -n 2 -r 48000 -s

It would appear that using a .jackdrc file doesn't work with your software, for whatever reason, so I just started Jack up manually.

I tried both 24 bit and 32 bit audio and it would seem the 32 bit audio takes less processing (as I would suspect anyway). I have a Behringer UMC404HD which is a 192kHz/24 bit device.

I see you have a long ways to go on the graphics! :) I don't really understand mixer page or stats page at all.

Anyway, a nice start. I do like the simplified processing chain.

**Comment by hselasky** [comment]
Some designs have been made to reduce the load on the server. This also includes how the mixer works.

**Comment by gilgongo** [comment]
Me on 1.0.8 (now I've got it to compile):

I take it there's no installers for other platforms yet, is that right? I'd like to try it out with some friends but they'd not be able to compile anything.

**Comment by hselasky** [comment]
Any updates?

**Comment by bflamig** [comment]
Hselasky,

 

I’ve been away from the Jamulus scene for a bit, so no I haven’t tried any of your new versions.

 

I’ll try to give it a go later in the week.

 

bryan
