### ISSUE TITLE
Windows binary: Cannot connect to ASIO subsystem

### ISSUE THREAD

**Issue by iFriendGit** [hselasky/hpsjam#7]
Hello HP!
thank you for the windows binary!
I tested it and it says: "Cannot connect to ASIO subsystem or sample rate is different from 48000 Hz or buffer size is different from 96 samples."

Actually, I cannto set my soundcard to 96, only 64 or 128, so I guess im lost here...?

**Comment by hselasky** [comment]
Try to press the toggle device button.
And make sure Asio4All is installed first.

**Comment by hselasky** [comment]
HpsJam will use 64 samples buffersize, if that is selected.

**Comment by iFriendGit** [comment]
i tried the toggle device, but it completely froze the window. I tried 128 but no no avail. Later today I will try 64.
I have a card-specific ASIO driver, so guess do not need ASIO4all

**Comment by iFriendGit** [comment]
just fyi, I tried a new version and got it working :)
