### ISSUE TITLE
Starting the server on Ubuntu 20.04 results in "Cannot bind to IP port: Address already in use"

### ISSUE THREAD

**Issue by oxytu** [hselasky/hpsjam#9]
Hi,

I created a dockerized version of your project for deployment to Amazon AWS. Unfortunately, I cannot get the server to run. I followed the exact instructions in the README and the port is definitively not in use (in fact, changing the port number to a random value always yields the same result), so I suspect that the implementation is broken in some way.

As the error message is wrong (port is free, verified by netstat) I cannot see any way to resolve this issue myself. Could you consider reviewing your code and maybe improving the error handling at this point to further track down the root cause?

You can find the docker image repository here and a deployed version in the linked DockerHub (See README).

https://github.com/oxytu/hpsjam-docker

Best Regards

**Comment by hselasky** [comment]
I think this commit will fix the issue:
https://github.com/hselasky/hpsjam/commit/0d207a47efa57c05201d1306c23d98dba62a3a49

--HPS

**Comment by oxytu** [comment]
Hi @hselasky - thank you that looks good, I just updated the latest-Image. I could start the server now. Unfortunately, I cannot connect to it. Can I send you the URL and you give it a try? I would do so by private message if possible.

**Comment by hselasky** [comment]
You can reach me at hps@selasky.org

**Comment by oxytu** [comment]
Is fixed with @hselasky commit.
